### ISSUE TITLE
Call for feedback (either positive or negative)

### ISSUE THREAD

**Issue by stefan-zobel** [retrostreams/android-retrostreams#1]
The current beta-1 version obviously needs more testing by different users.

I'd really appreciate if you would share your experience with me here.
Do you encounter any problems? Or not?

How does it feel to program with AS 3 against the new API? Is it really that much better (compared to streamsupport) that a separate fork is justifiable?

Please share your thoughts with me. If you encounter any bugs, I would very much welcome if you create an issue here. I'll look into any issue as soon as my work schedule permits.

Thanks in advance,
Stefan

**Comment by Quarx2k** [comment]
Hello, thanks for fork!
I just tested on 6.0, 7.1, 4.4, 4.2.  No problems for now 👍

**Comment by stefan-zobel** [comment]
Hi Nickolay @Quarx2k

Thanks for testing and letting me know!

Now, that's the first data point.

What would interest me: apart from the possibility of using AS 3 (which will probably also work with the original streamsupport Jar some day) do you see a significant advantage of the more Java 9 like API or are you more or less in the "I don't care that much" camp?

Thanks,
Stefan

**Comment by retrostreams** [comment]
@oasisfeng @Quarx2k @jdaberkow

I've released a release candidate (**RC-1**) of **android-retrostreams**: https://github.com/retrostreams/android-retrostreams/releases/tag/RC-1

As far as I can tell now, I'm through with internal improvements. As the Android Studio 3 beta 2 desugar toolchain appears pretty mature, an official stable release of android-retrostreams may not be far away.

Of course, I'd appreciate any feedback.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
@oasisfeng @Quarx2k @jdaberkow

A first "stable" release (**1.5.6**) of **android-retrostreams** is available now: https://github.com/retrostreams/android-retrostreams/releases/tag/1.5.6

Deployment to Maven Central will follow soon.

Regards,
Stefan

**Comment by Quarx2k** [comment]
Thanks! Works fine :)
